# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11wKV8_agJzcuqwS9dEiEJZ7uimPf0p44
"""

import streamlit as st
import joblib
import numpy as np
import pandas as pd
from agent import academic_agent

# ---------------- LOAD ----------------
features = joblib.load("/content/drive/MyDrive/features.pkl")
df = pd.read_csv("/content/drive/MyDrive/processed_data.csv")
means = df[features].mean()

# Human readable labels
LABELS = {
    "sex": "Gender",
    "age": "Age (years)",
    "address": "Residence Area",
    "Medu": "Mother's Education Level",
    "Fedu": "Father's Education Level",
    "traveltime": "Daily Travel Time (hrs)",
    "studytime": "Study Time (hrs)",
    "failures": "Past Academic Failures",
    "schoolsup": "Academic Support",
    "famsup": "Family Support",
    "paid": "Paid Extra Classes",
    "activities": "Extra Curricular Activities",
    "internet": "Internet Access",
    "freetime": "Free Time (hrs)",
    "goout": "Social Time (hrs)",
    "health": "Health Level",
    "absences": "Class Absences",
    "G1": "Second Last Semester SGPA",
    "G2": "Last Semester SGPA"
}

st.set_page_config(layout="wide")

# --------- Premium UI CSS ----------
st.markdown("""
<style>

.hero-card {
    background: linear-gradient(135deg, #020617, #0f172a);
    border-radius: 25px;
    padding: 30px;
    box-shadow: 0 15px 40px rgba(0,0,0,0.6);
}

.future-card {
    background: linear-gradient(135deg,#052e16,#064e3b);
    border-radius:25px;
    padding:30px;
    box-shadow:0 0 30px rgba(34,197,94,0.3);
}

.metric-big {
    font-size:48px;
    font-weight:800;
    color:#22c55e;
}

.metric-sub {
    color:#94a3b8;
}

.delta-pill {
    display:inline-block;
    background:#22c55e;
    color:black;
    padding:6px 14px;
    border-radius:20px;
    font-weight:600;
}

.action-box {
    background:#020617;
    border-left:6px solid #22c55e;
    padding:18px;
    border-radius:12px;
}

</style>
""", unsafe_allow_html=True)

st.title("🔮 FutureYou AI — Academic Twin")
st.caption("ML Prediction + Agentic Optimization")

st.sidebar.title("🧑‍🎓 Student Profile")

vals=[]

# ---------- SESSION INIT ----------
time_features=["studytime","traveltime","freetime","goout"]

for t in time_features:
    if t not in st.session_state:
        st.session_state[t]=float(means[t])

# ---------- CATEGORICAL ----------
sex=st.sidebar.selectbox(LABELS["sex"],["Female","Male"])
vals.append(1 if sex=="Male" else 0)

address=st.sidebar.selectbox(LABELS["address"],["Rural","Urban"])
vals.append(1 if address=="Urban" else 0)

yn_cols=["schoolsup","famsup","paid","activities","internet"]

for col in yn_cols:
    if col in features:
        c=st.sidebar.selectbox(LABELS[col],["No","Yes"])
        vals.append(1 if c=="Yes" else 0)

# ---------- HARD TIME CAP ----------
st.sidebar.markdown("### ⏰ Daily Time Budget (Max 20 hrs)")

prev={t:st.session_state[t] for t in time_features}

for t in time_features:
    st.sidebar.slider(LABELS[t],0.0,20.0,st.session_state[t],key=t)

total=sum(st.session_state[t] for t in time_features)

if total>20:
    for t in time_features:
        if st.session_state[t]!=prev[t]:
            st.session_state[t]=prev[t]
            break
    st.sidebar.error("🚨 Maximum 20 hours exceeded! Slider reverted.")

total=sum(st.session_state[t] for t in time_features)
st.sidebar.markdown(f"**Used:** {round(total,1)} / 20 hrs")

can_run=total<=20

for t in time_features:
    vals.append(st.session_state[t])

# ---------- NUMERIC ----------
skip=["sex","address"]+yn_cols+time_features

for col in features:
    if col in skip:
        continue

    if col=="age":
        a=st.sidebar.slider(LABELS[col],5,35,int(means[col]))
        vals.append(a)

    elif col in ["G1","G2"]:
        sg=st.sidebar.slider(LABELS[col],0.0,10.0,round(means[col]/2,2))
        vals.append(sg*2)

    elif col=="health":
        h=st.sidebar.slider(LABELS[col],0.0,10.0,round(means[col]*2,2))
        vals.append(h/2)

    else:
        vals.append(
            st.sidebar.slider(
                LABELS.get(col,col),
                float(df[col].min()),
                float(df[col].max()),
                float(means[col])
            )
        )

user=np.array(vals).reshape(1,-1)

# ---------- RUN ----------
if st.sidebar.button("Simulate Future") and can_run:

    baseline,action,improved,all_scenarios=academic_agent(user)

    base=round(baseline/20*10,2)
    imp=round(improved/20*10,2)
    delta=round(imp-base,2)

    c1,c2=st.columns(2)

    with c1:
        st.markdown("<div class='hero-card'>",unsafe_allow_html=True)
        st.markdown("### Predicted SGPA (Next Semester)")
        st.markdown(f"<div class='metric-big'>{base}</div>",unsafe_allow_html=True)
        st.markdown("<p class='metric-sub'>XGBoost Academic Forecast</p>",unsafe_allow_html=True)
        st.markdown("</div>",unsafe_allow_html=True)

    with c2:
        st.markdown("<div class='future-card'>",unsafe_allow_html=True)
        st.markdown("### Optimised SGPA (Next Semester)")
        st.markdown(f"<div class='metric-big'>{imp}</div>",unsafe_allow_html=True)
        st.markdown(f"<span class='delta-pill'>▲ +{delta} SGPA</span>",unsafe_allow_html=True)
        st.markdown("<p class='metric-sub'>Agent Simulated Future</p>",unsafe_allow_html=True)
        st.markdown("</div>",unsafe_allow_html=True)

    st.markdown("---")

    st.markdown("## 🔥 Personalised Recommendation")
    st.markdown(f"""
    <div class='action-box'>
    <h3>{action}</h3>
    <p>This change gives the maximum projected SGPA improvement.</p>
    </div>
    """,unsafe_allow_html=True)

    st.markdown("## 🌐 All Agent Futures")

    for a,s in all_scenarios:
        st.write(a,"→ SGPA:",round(s/20*10,2))

from pyngrok import ngrok
ngrok.kill()

ngrok.set_auth_token("38zFEFhZjyTg8aiAD4nkvh3CCkx_7VurjSSCgmd2ggfHCcGYZ")

!streamlit run app.py &>/content/logs.txt &

public_url = ngrok.connect(8501)
print(public_url)
